server:
  port: 8089
  servlet:
    context-path: /csrf

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csrf_test?serverTimezone=GMT%2B8
    username: root
    password: 111111

mybatis:
  type-aliases-package: package com.oudake.csrftest.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置驼峰下划线
    map-underscore-to-camel-case: true


